# Generated by Django 5.2.7 on 2025-11-24 13:03

import django.db.models.deletion
import video.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('total_likes', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=video.models.get_upload_path, verbose_name='Файл')),
                ('quality', models.CharField(choices=[('720p', 'HD (720p)'), ('1080p', 'Full HD (1080p)'), ('4K', 'Ultra HD (4K)')], max_length=10, verbose_name='Качество')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to='video.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Видеофайл',
                'verbose_name_plural': 'Видеофайлы',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='video.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'constraints': [models.UniqueConstraint(fields=('user', 'video'), name='unique_user_video_like')],
            },
        ),
    ]
