# Generated by Django 5.2.7 on 2025-11-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='videofile',
            constraint=models.UniqueConstraint(fields=('video', 'quality'), name='unique_video_quality_videofile'),
        ),
    ]
